language: python
python:
- '3.6'
cache:
- pip
notifications:
  email: false
install:
# pytest is already installed, we need a greater version
- pipenv install --dev
script:
- pipenv run pytest
branches:
  only:
    master
